### PR TITLE
footer

### PR DESCRIPTION
**Pull request by vermaanurag1532**

### CODE REVIEW

**Comment by aastha0326** [comment]
@vermaanurag1532 can you resolve conflicts?

**Comment by whiteHatpro** [comment]
@vermaanurag1532 I have resolved the conflicts
just check the files code again and then confirm here

**Comment by Gaurav-Verma07** [comment]
> @vermaanurag1532 I have resolved the conflicts just check the files code again and then confirm here

Sir @Tgsp31 is making some changes in footer.. once they're done I'll merge this PR

**Comment by Gaurav-Verma07** [comment]
This PR is further refactored by  shruti.

**Pull request closed without merging**
